name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug directory structure
        run: |
          pwd
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Inject VITE_API_SERVER
        run: echo "VITE_API_SERVER=${{ secrets.VITE_API_SERVER }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      # Clean up node_modules to reduce file count
      - name: Clean up node_modules
        run: rm -rf node_modules

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          app_location: "dist"  # Changed from "." to "dist"
          skip_app_build: true
          action: "upload"  # Added this line explicitly